
; Catppuccin Mocha
; main, sidebar, player = background
; card = cards, tracklist, dropdowns, input fields
; shadow = text on button, tab active & selected row
; selected row = selected song & tab
; button-active = play button, outline on focused input
; button = all other buttons
; button-disabled = volume & seekbar background, scrollbar handle, borders, hover

[catppuccin]
text               = cdd6f4
subtext            = a6adc8
main               = 1e1e2e
sidebar            = 1e1e2e
player             = 181825
card               = 313244
shadow             = 11111b
selected-row       = cba6f7
button             = 89b4fa
button-active      = 89b4fa
button-disabled    = 45475a
tab-active         = 89b4fa
notification       = 313244
notification-error = f38ba8
misc               = 11111b

[catppuccin]
text               = ea9a97
subtext            = f0c6c4
main               = 1E1E2E
sidebar            = 1E1E2E
player             = 161320
card               = 161320
shadow             = 161320
selected-row       = ea9a97
button             = ea9a97
button-active      = ea9a97
button-disabled    = 302D41
tab-active         = ea9a97
notification       = 161320
notification-error = F28FAD
misc               = 161320